 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;

import java.awt.Color;
import java.awt.GridBagLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Moheb
 */
public class Individual_Defaulter extends javax.swing.JDialog {

     public Connection conn() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:49172;"
                    + "databaseName=sscc;user=sa;password=sa9";
            return DriverManager.getConnection(url);
        } catch (SQLException | ClassNotFoundException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "An error occured while Connecting to Database.");
        }
        return null;
    }
    
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    Vector<String> header;
    Vector<Vector<String>> total = new Vector<Vector<String>>();
    public static JPanel Individual_Defaulter_panel = new JPanel(new GridBagLayout());
    String admission_date;
    
    
    /**
     * Creates new form Individual_Defaulter
     */
    public Individual_Defaulter(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        con = conn();
        
        try {
            ps = con.prepareStatement("select distinct Class from Fee_Info order by Class");
            rs = ps.executeQuery();
            while (rs.next()) {
                Cclass.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getLocalizedMessage());
        }
        
        header = new Vector<String>();
        header.add("Roll No");
        header.add("Name");
        header.add("Father Name");
        header.add("Class");
        header.add("Date");
        header.add("Fee Package");
        header.add("Fee");
        header.add("Fee Paid");
        header.add("Fee Debt");
        
        Tname.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Lclass = new javax.swing.JLabel();
        Cclass = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        Croll = new javax.swing.JComboBox<>();
        Bview = new javax.swing.JButton();
        Lname = new javax.swing.JLabel();
        Tname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Lclass.setText("Class                 :");

        Cclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Class" }));
        Cclass.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CclassItemStateChanged(evt);
            }
        });

        jLabel1.setText("Roll Number      :");

        Croll.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Roll Number" }));
        Croll.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CrollItemStateChanged(evt);
            }
        });

        Bview.setText("View");
        Bview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BviewActionPerformed(evt);
            }
        });

        Lname.setText("Name                :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Lclass)
                                .addGap(43, 43, 43)
                                .addComponent(Cclass, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(Lname))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Croll, 0, 205, Short.MAX_VALUE)
                                    .addComponent(Tname)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Bview, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cclass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lclass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Croll, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Tname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Lname, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addGap(7, 7, 7)))
                .addGap(18, 18, 18)
                .addComponent(Bview, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CclassItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CclassItemStateChanged
        Croll.removeAllItems();
        Croll.addItem("Select Roll Number");
        Tname.setText(null);
        
        try {
            ps = con.prepareStatement("select DISTINCT Roll_No from Fee_Info where Class='" + Cclass.getSelectedItem() + "' order by  Roll_No ASC");
            rs = ps.executeQuery();
            while (rs.next()) {
                Croll.addItem(rs.getString(1));
                }
            } catch (SQLException ex) {
                //JOptionPane.showMessageDialog(rootPane, ex.getLocalizedMessage());
            }
        
        CrollItemStateChanged(evt);
    }//GEN-LAST:event_CclassItemStateChanged

    private void CrollItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CrollItemStateChanged
        if(Croll.getSelectedIndex() == 0)
        {
            Tname.setText(null);
        }
        
        try {
            ps = con.prepareStatement("select Name from Fee_Info where Class='" + Cclass.getSelectedItem() + "' and Roll_No="+Croll.getSelectedItem());
            rs = ps.executeQuery();
            while (rs.next()) {
                Tname.setText(rs.getString(1));
                }
            } catch (SQLException ex) {
            } 
    }//GEN-LAST:event_CrollItemStateChanged

    private void BviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BviewActionPerformed
        String current_date;
        Date date1 = new Date();
        SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd");
        current_date = ft.format(date1);
        
        try {
            ps = con.prepareStatement("select Date_of_admission from Basic_info where Class = '"+Cclass.getSelectedItem()+"' and Roll_No = "+Croll.getSelectedItem());
            rs = ps.executeQuery();
            while (rs.next()) {
                admission_date = rs.getString(1);
                }
            } catch (SQLException ex) {
            } 
        
        try {
            ps = con.prepareStatement("SELECT * FROM Fee_Info where Roll_No = "+Croll.getSelectedItem()+" and Class = '"+Cclass.getSelectedItem()+"' and Date_of_Entry between '"+admission_date+"' and '"+current_date+"' order by YEAR(Date_of_Entry), MONTH(Date_of_Entry)");
            rs = ps.executeQuery();
            while (rs.next()) {
                Vector<String> data = new Vector<String>();
                    data.add(rs.getString(1));
                    data.add(rs.getString(2));
                    data.add(rs.getString(3));
                    data.add(rs.getString(4));
                    data.add(rs.getString(5));
                    data.add(rs.getString(7));
                    data.add(rs.getString(9));
                    data.add(rs.getString(10));
                    data.add(rs.getString(11));
                    total.add(data);
                    
                    Menu.Individual_Defaulter_table.setModel(new DefaultTableModel(
                        total, header) {
                            public boolean isCellEditable(int row, int col) {
                                return false;
                            }

                        }
                );
                }
            } catch (SQLException ex) {
            }
        
            Menu.Individual_Defaulter_table.setRowHeight(25);
            Menu.Individual_Defaulter_table.getColumnModel().getColumn(0).setMaxWidth(50);
            Menu.Individual_Defaulter_table.getColumnModel().getColumn(0).setMinWidth(50);
            Menu.Individual_Defaulter_table.getColumnModel().getColumn(1).setMaxWidth(65);
            Menu.Individual_Defaulter_table.getColumnModel().getColumn(1).setMinWidth(65);
            Menu.Individual_Defaulter_table.getColumnModel().getColumn(2).setMaxWidth(140);
            Menu.Individual_Defaulter_table.getColumnModel().getColumn(2).setMinWidth(140);
            Menu.Individual_Defaulter_table.getColumnModel().getColumn(3).setMaxWidth(60);
            Menu.Individual_Defaulter_table.getColumnModel().getColumn(3).setMinWidth(60);
            Menu.Individual_Defaulter_table.getColumnModel().getColumn(4).setMaxWidth(70);
            Menu.Individual_Defaulter_table.getColumnModel().getColumn(4).setMinWidth(70);
            Menu.Individual_Defaulter_table.getColumnModel().getColumn(5).setMaxWidth(80);
            Menu.Individual_Defaulter_table.getColumnModel().getColumn(5).setMinWidth(80);
            Menu.Individual_Defaulter_table.getColumnModel().getColumn(6).setMaxWidth(50);
            Menu.Individual_Defaulter_table.getColumnModel().getColumn(6).setMinWidth(50);
            Menu.Individual_Defaulter_table.getColumnModel().getColumn(7).setMaxWidth(60);
            Menu.Individual_Defaulter_table.getColumnModel().getColumn(7).setMinWidth(60);
            Menu.Individual_Defaulter_table.getColumnModel().getColumn(8).setMaxWidth(60);
            Menu.Individual_Defaulter_table.getColumnModel().getColumn(8).setMinWidth(60);
            
            Menu.Individual_Defaulter_table.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
            Individual_Defaulter_panel.setPreferredSize(Menu.Tab.getSize());
            Individual_Defaulter_panel.setBackground(Color.WHITE);
            Individual_Defaulter_panel.add(Menu.Individual_Defaulter);
            Individual_Defaulter_panel.setName("Individual Defaulter List");
            
            Menu.Tab.setVisible(true);
            Menu.Tab.add(Individual_Defaulter_panel);
            
            Menu.Tab.setSelectedComponent(Individual_Defaulter_panel);
            Icon icon = new ImageIcon(getClass().getResource("/Images/details.png"));
            Menu.Tab.setIconAt(Menu.Tab.getSelectedIndex(), icon);
            this.setVisible(false);
        
        
    }//GEN-LAST:event_BviewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Individual_Defaulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Individual_Defaulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Individual_Defaulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Individual_Defaulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Individual_Defaulter dialog = new Individual_Defaulter(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bview;
    private javax.swing.JComboBox<String> Cclass;
    private javax.swing.JComboBox<String> Croll;
    private javax.swing.JLabel Lclass;
    private javax.swing.JLabel Lname;
    private javax.swing.JTextField Tname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
