/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;


import java.awt.Color;
import java.awt.GridBagLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Moheb
 */
public class Overall_Defaulte extends javax.swing.JDialog {
   public Connection conn() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:49172;"
                    + "databaseName=sscc;user=sa;password=sa9";
            return DriverManager.getConnection(url);
        } catch (SQLException | ClassNotFoundException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "An error occured while Connecting to Database.");
        }
        return null;
    }
    
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    Vector<String> header;
    Vector<Vector<String>> total = new Vector<Vector<String>>();
    public static JPanel Overall_Defaulter_panel = new JPanel(new GridBagLayout());
    String date;
    int year, month, date1;
    String sprevious_year, scurrent_year, sprevious_month, scurrent_month, sprevious_date, scurrent_date;
    
    public Overall_Defaulte(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        con = conn();
        
        header = new Vector<String>();
        header.add("Roll No");
        header.add("Name");
        header.add("Father Name");
        header.add("Class");
        header.add("Date");
        header.add("Fee Package");
        header.add("Fee");
        header.add("Fee Paid");
        header.add("Fee Debt");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Ldate = new javax.swing.JLabel();
        Date = new com.toedter.calendar.JDateChooser();
        Bshow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Ldate.setText("Date         :");

        Bshow.setText("View");
        Bshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BshowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bshow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Ldate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Ldate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Date, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bshow, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BshowActionPerformed
        if(Date.getDate() == null)
        {
            JOptionPane.showMessageDialog(rootPane, "Please Select Date First.");
        }
        else
        {
            SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd");
            date = ft.format(Date.getDate());
            
            //splitting date and assigning it to variables
            String[] y_m_d = date.split("-");
            year = Integer.parseInt(y_m_d[0]);
            month = Integer.parseInt(y_m_d[1]);
            date1 = Integer.parseInt(y_m_d[2]);
            
            if (month == 1)
        {
            sprevious_month = "12";
            scurrent_month = "0"+Integer.toString(month);
            sprevious_year = Integer.toString(year - 1);
            scurrent_year = Integer.toString(year);
            sprevious_date = scurrent_date = Integer.toString(date1);
            
        }
        else if (month == 11 || month == 12)
        {
            sprevious_month = Integer.toString(month - 1);
            scurrent_month = Integer.toString(month);
            sprevious_year = scurrent_year = Integer.toString(year);
            sprevious_date = scurrent_date = Integer.toString(date1);
        }
        else if (month == 10)
        {
            sprevious_month = "0"+Integer.toString(month - 1);
            scurrent_month = Integer.toString(month);
            sprevious_year = scurrent_year = Integer.toString(year);
            sprevious_date = scurrent_date = Integer.toString(date1);
        }
        else
        {
            sprevious_month = "0"+Integer.toString(month - 1);
            scurrent_month = "0"+Integer.toString(month);
            sprevious_year = scurrent_year = Integer.toString(year);
            sprevious_date = scurrent_date = Integer.toString(date1);
        }
        
            
            try {
                ps = con.prepareStatement("SELECT * FROM Fee_Info where Date_of_Entry between '" + sprevious_year+"-"+sprevious_month+"-"+sprevious_date+"' and '"+scurrent_year+"-"+scurrent_month+"-"+scurrent_date+"' and (Calculated_Fee != Fee_Paid and Fee_Debt > 0) order by Class asc, Roll_No asc");
                rs = ps.executeQuery();
                while (rs.next()) {
                    Vector<String> data = new Vector<String>();
                    data.add(rs.getString(1));
                    data.add(rs.getString(2));
                    data.add(rs.getString(3));
                    data.add(rs.getString(4));
                    data.add(rs.getString(5));
                    data.add(rs.getString(7));
                    data.add(rs.getString(9));
                    data.add(rs.getString(10));
                    data.add(rs.getString(11));
                    total.add(data);
                }
                
                Menu.Overall_Defaulter_table.setModel(new DefaultTableModel(
                        total, header) {
                            public boolean isCellEditable(int row, int col) {
                                return false;
                            }

                        }
                );
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getLocalizedMessage());
            }
            
            Menu.Overall_Defaulter_table.setRowHeight(25);
            Menu.Overall_Defaulter_table.getColumnModel().getColumn(0).setMaxWidth(50);
            Menu.Overall_Defaulter_table.getColumnModel().getColumn(0).setMinWidth(50);
            Menu.Overall_Defaulter_table.getColumnModel().getColumn(1).setMaxWidth(65);
            Menu.Overall_Defaulter_table.getColumnModel().getColumn(1).setMinWidth(65);
            Menu.Overall_Defaulter_table.getColumnModel().getColumn(2).setMaxWidth(140);
            Menu.Overall_Defaulter_table.getColumnModel().getColumn(2).setMinWidth(140);
            Menu.Overall_Defaulter_table.getColumnModel().getColumn(3).setMaxWidth(60);
            Menu.Overall_Defaulter_table.getColumnModel().getColumn(3).setMinWidth(60);
            Menu.Overall_Defaulter_table.getColumnModel().getColumn(4).setMaxWidth(70);
            Menu.Overall_Defaulter_table.getColumnModel().getColumn(4).setMinWidth(70);
            Menu.Overall_Defaulter_table.getColumnModel().getColumn(5).setMaxWidth(80);
            Menu.Overall_Defaulter_table.getColumnModel().getColumn(5).setMinWidth(80);
            Menu.Overall_Defaulter_table.getColumnModel().getColumn(6).setMaxWidth(50);
            Menu.Overall_Defaulter_table.getColumnModel().getColumn(6).setMinWidth(50);
            Menu.Overall_Defaulter_table.getColumnModel().getColumn(7).setMaxWidth(60);
            Menu.Overall_Defaulter_table.getColumnModel().getColumn(7).setMinWidth(60);
            Menu.Overall_Defaulter_table.getColumnModel().getColumn(8).setMaxWidth(60);
            Menu.Overall_Defaulter_table.getColumnModel().getColumn(8).setMinWidth(60);
            
            Menu.Overall_Defaulter_table.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
            Overall_Defaulter_panel.setPreferredSize(Menu.Tab.getSize());
            Overall_Defaulter_panel.setBackground(Color.WHITE);
            Overall_Defaulter_panel.add(Menu.Overall_Defaulter);
            Overall_Defaulter_panel.setName("Overall Defaulter List");
            
            Menu.Tab.setVisible(true);
            Menu.Tab.add(Overall_Defaulter_panel);
            
            Menu.Tab.setSelectedComponent(Overall_Defaulter_panel);
            Icon icon = new ImageIcon(getClass().getResource("/Images/details.png"));
            Menu.Tab.setIconAt(Menu.Tab.getSelectedIndex(), icon);
            Date.setCalendar(null);
            this.setVisible(false);
        }
    }//GEN-LAST:event_BshowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Overall_Defaulte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Overall_Defaulte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Overall_Defaulte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Overall_Defaulte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Overall_Defaulte dialog = new Overall_Defaulte(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bshow;
    private com.toedter.calendar.JDateChooser Date;
    private javax.swing.JLabel Ldate;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
