/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;

import static MainPackage.View_monthlyresult.Monthly_Result_panel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridBagLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author asadj
 */
public class view_Weeklygraph extends javax.swing.JDialog {
    public Connection conn() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:49172;"
                    + "databaseName=sscc;user=sa;password=sa9";
            return DriverManager.getConnection(url);
        } catch (SQLException | ClassNotFoundException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "An error occured while Connecting to Database.");
        }
        return null;
    }
  public static JPanel panel = new JPanel(new GridBagLayout());

  public static JPanel Weekly_graph = new JPanel(new GridBagLayout());
   String[] str = {"January",      
   "February",
   "March",        
   "April",        
   "May",          
   "June",         
   "July",         
   "August",       
   "September",    
   "October",      
   "November",     
   "December"};

Connection con;
PreparedStatement ps;
ResultSet rs;
    /**
     * Creates new form view_Weeklygraph
     */
    public view_Weeklygraph(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         try{
            con=conn();
        }
        catch(Exception ex ){
            JOptionPane.showMessageDialog(rootPane, ex.getLocalizedMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Grade1 = new javax.swing.JComboBox();
        RollNo1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Name1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Month_view_weekly = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jLabel12.setText("Class:");

        Grade1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "IX-A", "X-A", "X-B", "XI-A", "XI-B", "XII-A", "XI-Commerce", "XII-Commerce", "B.com-I", "B.com-II" }));
        Grade1.setMaximumSize(null);
        Grade1.setMinimumSize(new java.awt.Dimension(50, 25));
        Grade1.setPreferredSize(new java.awt.Dimension(50, 25));
        Grade1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Grade1ItemStateChanged(evt);
            }
        });

        RollNo1.setMaximumSize(null);
        RollNo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RollNo1ItemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jLabel8.setText("Roll Number:");

        jLabel9.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jLabel9.setText("Name:");

        Name1.setEditable(false);
        Name1.setBackground(new java.awt.Color(255, 255, 255));
        Name1.setMaximumSize(null);
        Name1.setMinimumSize(new java.awt.Dimension(6, 23));

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jLabel14.setText("Month:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Month_view_weekly, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Grade1, 0, 216, Short.MAX_VALUE)
                            .addComponent(RollNo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Name1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Grade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(RollNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(Name1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(Month_view_weekly, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Grade1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Grade1ItemStateChanged
        RollNo1.removeAllItems();
     Vector v=new Vector();
                
        try {
            ps = con.prepareStatement("select [Roll_No] from Basic_info where Class='" + Grade1.getSelectedItem() + "' order by  Roll_No ASC");
            rs = ps.executeQuery();
            while (rs.next()) {
                String list = rs.getString("Roll_No");
                v.add(list);

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getLocalizedMessage());
        }
        final DefaultComboBoxModel model = new DefaultComboBoxModel(v);
        RollNo1.setModel(model);
        RollNo1ItemStateChanged(null);
    }//GEN-LAST:event_Grade1ItemStateChanged

    private void RollNo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RollNo1ItemStateChanged

        Name1.setText(null);
        try {
            ps = con.prepareStatement("select Name from Basic_info where Roll_No='" + RollNo1.getSelectedItem() + "' AND Class='" + Grade1.getSelectedItem() + "'");
            rs = ps.executeQuery();
            while (rs.next()) {
                Name1.setText(rs.getString(1));
            }
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_RollNo1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
      if (Name1.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "PLEASE SELECET ROLL NUMBER");
        } else {
          ArrayList<String> Subject=new ArrayList();
         DefaultCategoryDataset barchart= new DefaultCategoryDataset();
       int index = Arrays.asList(str).indexOf(Month_view_weekly.getSelectedItem());
    
       try{
       ps=con.prepareStatement("Select DISTINCT Subject from WeeklyTestTable where Roll_No=" + RollNo1.getSelectedItem() + " AND Class='" + Grade1.getSelectedItem() + "' AND month(Date_of_Entry)=" + (index + 1) + "");
       rs=ps.executeQuery();
       while(rs.next()){
       Subject.add(rs.getString(1));
       }
       }catch(SQLException ex){
       
       }
       
       
       
       
       
       
       
       for(int i=0; i<Subject.size(); i++){
       int j=1;
           try {
                
                ps = con.prepareStatement("Select  Subject,Marks from WeeklyTestTable where Roll_No=" + RollNo1.getSelectedItem() + " AND Class='" + Grade1.getSelectedItem() + "' AND month(Date_of_Entry)=" + (index + 1) + " AND Subject='"+Subject.get(i)+"'");
                rs = ps.executeQuery();
                while (rs.next()) {  
                    String sub=rs.getString(1);
                    if(sub.equals("Pakistan Studies")){
                    barchart.addValue(rs.getFloat(2), "Marks", "Pst "+(j));    
                    }
                    else if(sub.equals("Mathematics")){
                    barchart.addValue(rs.getFloat(2), "Marks", "Maths "+(j));    
                    }
                    else if(sub.equals("Biology")){
                    barchart.addValue(rs.getFloat(2), "Marks", "Bio "+(j));    
                    }
                    else if(sub.equals("Chemistry")){
                        barchart.addValue(rs.getFloat(2), "Marks", "Chem "+(j));
                    }
                    else if(sub.equals("Physics")){
                    barchart.addValue(rs.getFloat(2), "Marks", "Phy "+(j));
                    }
                     else if(sub.equals("Islamiat")){
                    barchart.addValue(rs.getFloat(2), "Marks", "Isl "+(j));
                    }
                     else if(sub.equals("English")){
                    barchart.addValue(rs.getFloat(2), "Marks", "Eng "+(j));
                    }
                    else{
                    barchart.addValue(rs.getFloat(2), "Marks", sub+" "+(j));
                    }
                    j++;
                    
                }
            }
           catch(SQLException ex){
                   
                   
                   
            }     
        
       }
        JFreeChart bar6=ChartFactory.createBarChart("SIR SYED COACHING CENTER\nName: "+Name1.getText()+"\nClass:"+Grade1.getSelectedItem()+"\nRoll Number:"+RollNo1.getSelectedItem()+"", "WEEKLY TEST REPORT OF MONTH "+Month_view_weekly.getSelectedItem().toString().toUpperCase(), "BAR CHART", barchart,PlotOrientation.VERTICAL,false,true,false);
        CategoryPlot barchrt6=bar6.getCategoryPlot();
        barchrt6.setRangeGridlinePaint(Color.BLACK);
        ChartPanel panel=new ChartPanel(bar6);
        Menu.Weeklygraph.removeAll();
        Menu.Weeklygraph.add(panel, BorderLayout.CENTER);
        Menu.Weeklygraph.validate();
        
        this.setVisible(false);
        Menu.Tab.add(Menu.Weeklygraph);
        //Menu.Weeklygraph.setName("WEEKLY TEST REPORT OF MONTH "+Month_view_weekly.getSelectedItem().toString().toUpperCase());
        Menu.Tab.setSelectedComponent(Menu.Weeklygraph);
        ImageIcon icon=new ImageIcon("src//Images//print.png");
        Menu.Tab.setIconAt(Menu.Tab.getSelectedIndex(), icon);
        Menu.Tab.setVisible(true);
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_Weeklygraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_Weeklygraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_Weeklygraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_Weeklygraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                view_Weeklygraph dialog = new view_Weeklygraph(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox Grade1;
    public javax.swing.JComboBox Month_view_weekly;
    public javax.swing.JTextField Name1;
    public javax.swing.JComboBox RollNo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
