/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;

import java.awt.Color;
import java.awt.GridBagLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asadj
 */
public class Viewmonthly_weeklyresult extends javax.swing.JDialog {

    /**
     * Creates new form Viewmonthly_weeklyresult
     */
    Vector<Vector<String>> total = new Vector<Vector<String>>();
    public static JPanel Weeklymonthly_Result_panel = new JPanel(new GridBagLayout());
    Vector<String> header;
     public Connection conn() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:49172;"
                    + "databaseName=sscc;user=sa;password=sa9";
            return DriverManager.getConnection(url);
        } catch (SQLException | ClassNotFoundException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "An error occured while Connecting to Database.");
        }
        return null;
    }
    String[] str = {"January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December"};

    Connection con;
    PreparedStatement ps;
    ResultSet rs;

    
    public Viewmonthly_weeklyresult(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        header = new Vector<String>();
        header.add("Roll No.");
        header.add("Class");
        header.add("Name");
        header.add("Date Of Entry");
        header.add("Marks");
        header.add("Subject");
        con = conn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MonthResult = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        GradeReslut_view = new javax.swing.JComboBox();
        Weekly_result_view = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        RollNo1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Name1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        MonthResult.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jLabel13.setText("Class:");

        jLabel14.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jLabel14.setText("Month:");

        GradeReslut_view.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "IX-A", "X-A", "X-B", "XI-A", "XI-B", "XII-A", "XI-Commerce", "XII-Commerce", "B.com-I", "B.com-II" }));
        GradeReslut_view.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                GradeReslut_viewItemStateChanged(evt);
            }
        });

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        RollNo1.setMaximumSize(null);
        RollNo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RollNo1ItemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jLabel8.setText("Roll Number:");

        jLabel9.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jLabel9.setText("Name:");

        Name1.setEditable(false);
        Name1.setBackground(new java.awt.Color(255, 255, 255));
        Name1.setMaximumSize(null);

        javax.swing.GroupLayout MonthResultLayout = new javax.swing.GroupLayout(MonthResult);
        MonthResult.setLayout(MonthResultLayout);
        MonthResultLayout.setHorizontalGroup(
            MonthResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MonthResultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MonthResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MonthResultLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MonthResultLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Weekly_result_view, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MonthResultLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GradeReslut_view, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MonthResultLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(RollNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        MonthResultLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {GradeReslut_view, Name1, RollNo1, Weekly_result_view});

        MonthResultLayout.setVerticalGroup(
            MonthResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MonthResultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MonthResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(GradeReslut_view, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(MonthResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(RollNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MonthResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Name1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MonthResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Weekly_result_view, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MonthResultLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {GradeReslut_view, Name1, RollNo1, Weekly_result_view});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MonthResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MonthResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GradeReslut_viewItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_GradeReslut_viewItemStateChanged
  Vector v=new Vector();
        try {
            ps = con.prepareStatement("select [Roll_No] from Basic_info where Class='" + GradeReslut_view.getSelectedItem() + "' order by  Roll_No ASC");
            rs = ps.executeQuery();
           while (rs.next()) {
                String list = rs.getString("Roll_No");
                v.add(list);

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getLocalizedMessage());
        }
        final DefaultComboBoxModel model = new DefaultComboBoxModel(v);
        RollNo1.setModel(model);
        RollNo1ItemStateChanged(evt);

        Weekly_result_view.removeAllItems();
        try {
            ps = con.prepareStatement("select DISTINCT month(Date_of_Entry),year(Date_of_Entry) from WeeklyTestTable where Class='" + GradeReslut_view.getSelectedItem() + "'");
            rs = ps.executeQuery();
            while (rs.next()) {
                Weekly_result_view.addItem(str[rs.getInt(1) - 1]);
            }
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_GradeReslut_viewItemStateChanged

    private void RollNo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RollNo1ItemStateChanged

        Name1.setText(null);
        try {
            ps = con.prepareStatement("select Name from Basic_info where Roll_No='" + RollNo1.getSelectedItem() + "' AND Class='" + GradeReslut_view.getSelectedItem() + "'");
            rs = ps.executeQuery();
            while (rs.next()) {
                Name1.setText(rs.getString(1));
            }
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_RollNo1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (Name1.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "PLEASE SELECET ROLL NUMBER");
        } else {
            int index = Arrays.asList(str).indexOf(Weekly_result_view.getSelectedItem());
            try {
                ps = con.prepareStatement("Select * from WeeklyTestTable where Roll_No=" + RollNo1.getSelectedItem() + " AND Class='" + GradeReslut_view.getSelectedItem() + "' AND month(Date_of_Entry)=" + (index + 1) + "");
                rs = ps.executeQuery();
                while (rs.next()) {
                    Vector<String> data = new Vector<String>();
                    data.add(rs.getString(1));
                    data.add(rs.getString(2));
                    data.add(rs.getString(3));
                    data.add(rs.getString(4));
                    data.add(rs.getString(5));
                    data.add(rs.getString(6));
                    total.add(data);
                }

                Menu.Weekly_monthly_table.setModel(new DefaultTableModel(
                        total, header) {
                            public boolean isCellEditable(int row, int col) {
                                return false;
                            }

                        }
                );

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getLocalizedMessage());
            }

            Menu.Weekly_monthly_table.setRowHeight(25);
            Menu.Weekly_monthly_table.getColumnModel().getColumn(0).setMaxWidth(55);
            Menu.Weekly_monthly_table.getColumnModel().getColumn(0).setMinWidth(55);
            Menu.Weekly_monthly_table.getColumnModel().getColumn(1).setMaxWidth(55);
            Menu.Weekly_monthly_table.getColumnModel().getColumn(1).setMinWidth(55);
            Menu.Weekly_monthly_table.getColumnModel().getColumn(2).setMaxWidth(200);
            Menu.Weekly_monthly_table.getColumnModel().getColumn(2).setMinWidth(200);
            Menu.Weekly_monthly_table.getColumnModel().getColumn(3).setMaxWidth(100);
            Menu.Weekly_monthly_table.getColumnModel().getColumn(3).setMinWidth(100);
            Menu.Weekly_monthly_table.getColumnModel().getColumn(4).setMaxWidth(55);
            Menu.Weekly_monthly_table.getColumnModel().getColumn(4).setMinWidth(55);
            Menu.Weekly_monthly_table.getColumnModel().getColumn(5).setMaxWidth(100);
            Menu.Weekly_monthly_table.getColumnModel().getColumn(5).setMinWidth(100);

            Menu.Weekly_monthly_table.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
            Weeklymonthly_Result_panel.setPreferredSize(Menu.Tab.getSize());
            Weeklymonthly_Result_panel.setBackground(Color.WHITE);
            Weeklymonthly_Result_panel.add(Menu.Monthly_weekly);
            Weeklymonthly_Result_panel.setName("Monthly Weekly Results");

            Menu.Tab.setVisible(true);
           Icon icon = new ImageIcon(getClass().getResource("/Images/details.png"));
            
             Menu.Tab.add(Weeklymonthly_Result_panel);
            
            Menu.Tab.setSelectedComponent(Weeklymonthly_Result_panel);
            Menu.Tab.setIconAt(Menu.Tab.getSelectedIndex(), icon);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viewmonthly_weeklyresult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viewmonthly_weeklyresult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viewmonthly_weeklyresult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viewmonthly_weeklyresult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Viewmonthly_weeklyresult dialog = new Viewmonthly_weeklyresult(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox GradeReslut_view;
    private javax.swing.JPanel MonthResult;
    public javax.swing.JTextField Name1;
    public javax.swing.JComboBox RollNo1;
    public javax.swing.JComboBox Weekly_result_view;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
